mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=sunnyuser
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=sunnyrefdata
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"