package com.sunny.refdata;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/sunny") // This means URL's start with /refdata (after Application path)
public class RefDataController {
	@Autowired // This means to get the bean called refDataRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private RefDataService refDataService;
	
	
	@RequestMapping(value = "/refdata", method = RequestMethod.GET)
    public List<RefData> getRefDatas() {
		return refDataService.getAllRefDatas();
	}
	
	@RequestMapping(value = "/refdata/{id}", method = RequestMethod.GET)
    public RefData getEmployee(@PathVariable("id") long id) {
		return refDataService.getRefDataById(id);
	}
	
}
